### ISSUE TITLE
Data visualization page

### ISSUE THREAD

**Issue by ango0512** [ianrabt/wpa#21]

**Comment by hmc-cs-jraygoza** [comment]
This task could probably be broken down a bit.

**Comment by ianrabt** [comment]
I will break this down...and will assign myself to the various parts.

**Comment by ianrabt** [comment]
- [ ] create fragment
- [ ] research and find a graphing library
- [ ] get statistical data from the firebase repository
- [ ] create controller for graph view to plot data from repository
